### ISSUE TITLE
Various Questions

### ISSUE THREAD

**Issue by xiao666** [philipperemy/financial-news-dataset#1]

**Comment by philipperemy** [comment]
Hey! Where do you see the pickle files?

**Comment by xiao666** [comment]
im doing my thesis on NLP application on stock prediction, just searched related dataset, and find here : )

**Comment by philipperemy** [comment]
Oh yeah you're referring to the Reuters data set?

github.com/philipperemy/Reuters-full-data-set

**Comment by xiao666** [comment]
yes, the problem was the python version. I can load the headlines now.
just a bit more questions about the  details of news dataset, 
1. each day may consists of different number of news right?
2. and if I want to use these news to make stock prediction, how to align the news with market performance together? depend on the same date?

**Comment by philipperemy** [comment]
Each news has a precise datetime.

For example this one:
```
ts = 20070228 11:46 AM EST, t = European stocks hit 7-week low amid new sell-off, h= http://www.reuters.com/article/companyNewsAndPR/idUSWEB277620070228
```

was published on February 28th 2007 at 11:46 AM (Eastern Time Zone).

You can align the news with the market performance by:
- aggregating the news per day.

Or if you have 1 min price data, you don't need to aggregate.
